### ISSUE TITLE
MT-32 titles are downloaded every time

### ISSUE THREAD

**Issue by djfumberger** [mrchrisster/0mhz-collection#1]
I have prefers_mt32 set to true, and each time I run the downloader the MT-32 folders are flagged as missing and are re-downloaded.

Also thanks for the script, really useful!

**Comment by djfumberger** [comment]
I think also related to this is I'm seeing a .mgl for both the standard and mt32 version being created in "_DOS Games" when ideally I'd assume only the .mgl for the mt32 version should be added to there when prefers_mt32 is true. 

Or if this assumption isn't true, it could be nice to have an additional flag to specify only mt32 mgl's in the case where there will be two.

**Comment by mrchrisster** [comment]
just working on that. can you test if https://github.com/mrchrisster/0mhz-collection/blob/main/0mhz_downloader-wip.sh
works as expected?

**Comment by djfumberger** [comment]
Just ran it and can confirm it didn't redownload unchanged / existing mt-32 files. Cheers
