### ISSUE TITLE
Downloader script creates media/fat/games/ao486/media even when path is set to media/usb0

### ISSUE THREAD

**Issue by rsn8887** [mrchrisster/0mhz-collection#2]
See title. I think this line should be deleted:
https://github.com/mrchrisster/0mhz-collection/blob/ddfa3ecd626cbbc29153a3160bb77d5deaca7c3e/0mhz_downloader.sh#L47

**Comment by mrchrisster** [comment]
Someone mentioned the path needs to exist on fat even if you use usb. I agree though, not sure behind the logic, so i'll take it out for now
